@startuml
'https://plantuml.com/class-diagram
hide empty members

namespace Вариант_1 {
    interface I_Interface1
    interface I_Interface2
    interface I_Interface3

    interface I_ExtInt1 extends I_Interface1

    interface I_ExtInt2And3 extends I_Interface2
    interface I_ExtInt2And3 extends I_Interface3
}


together {
abstract AC_AbsClass

abstract AC_ImplInt1 implements I_Interface1

abstract AC_ImplInt1And2 implements I_Interface1
abstract AC_ImplInt1And2 implements I_Interface2

abstract AC_ImplInt1And2And3 implements I_Interface1
abstract AC_ImplInt1And2And3 implements I_Interface2
abstract AC_ImplInt1And2And3 implements I_Interface3
}


@enduml